export const JOBS = [
    {
        id: '1',
        title: 'Frontend developer',
        postedAt: '03/06/2022 at 10:30',
        category: 'technology',
        skills: ['reactJS,nextJS,figma,communication, leadership,leadership'],
        organisation: 'Microsoft',
        smallDescription: 'Responsible for implementing visual and interactive elements that users engage with through their web browser when using a web application.',
    },
    {
        id: '2',
        title: 'Bartender',
        postedAt: '01/06/2022 at 13:00',
        category: 'service',
        skills: ['not required'],
        organisation: 'Jeffs pub',
        smallDescription: 'Service professional who prepares and serves alcoholic and non-alcoholic beverages.',
    },
    {
        id: '3',
        title: 'Marketing specialist',
        postedAt: '03/05/2022 at 12:30',
        category: 'marketing',
        skills: ['communication, social'],
        organisation: 'Klarna',
        smallDescription: 'You can send a request for housing with your info, our organisation will review the request and get back to you as soon as possible.',
    },
    {
        id: '4',
        title: 'Frontend developer',
        postedAt: '03/06/2022 at 10:30',
        category: 'technology',
        skills: ['reactJS,nextJS,figma,communication, leadership'],
        organisation: 'Klarna',
        smallDescription: 'Learn our language, from basic to advanced, you will be able to accomplish first interactions with our citiziens.',
    },
    {
        id: '5',
        title: 'Cleaner',
        postedAt: '31/05/2022 at 16:00',
        category: 'service',
        skills: ['experience required'],
        organisation: 'Hotel Infinity',
        smallDescription: 'Performs cleaning duties in all guest areas and back of house.',
    },
    {
        id: '6',
        title: 'Bartender',
        postedAt: '01/06/2022 at 13:00',
        category: 'service',
        skills: ['experience in making coctels'],
        organisation: 'Pub Forzza',
        smallDescription: 'Service professional who prepares and serves alcoholic and non-alcoholic beverages.',
    },
    {
        id: '7',
        title: 'Backend developer',
        postedAt: '02/06/2022 at 09:30',
        category: 'technology',
        skills: ['nodeJS,nestJS,web sockets, AWS, dynamoDB'],
        organisation: 'Apple',
        smallDescription: 'As a Back-end developer, you will work closely with our engineers to ensure system consistency and improve user experience.',
    },
    {
        id: '8',
        title: 'Marketing specialist',
        postedAt: '03/05/2022 at 12:30',
        category: 'marketing',
        skills: ['communication, social'],
        organisation: 'Klarna',
        smallDescription: 'You can send a request for housing with your info, our organisation will review the request and get back to you as soon as possible.',
    },
];